### ISSUE TITLE
Quick Question: Have you ever tried distill the instruction-tuned models? If so, will the instruction following capabilities remain? 

### ISSUE THREAD

**Issue by Mooler0410** [jxiw/MambaInLlama#1]
Thanks!

**Comment by jxiw** [comment]
Yes. The teacher model is instruct tuned model. We are still on the way to release everything and hope to get ready this week or next week. Stay tuned. Thanks.

**Comment by jxiw** [comment]
Hi, please check our paper here.  https://arxiv.org/abs/2408.15237
if you have any further question, please let me know. thanks.
