### ISSUE TITLE
The difference between Mamba and Mamba_inference directories

### ISSUE THREAD

**Issue by 1773226512** [jxiw/MambaInLlama#10]
Thank you for your excellent work. I have a question regarding the models found in the mamba and mamba_inference directories. Could you please clarify the differences between these two sets of models? Specifically:

Are there any architectural or implementation differences between the models in these two directories?
Do these models serve different purposes or are optimized for different use cases?
Any clarification would be greatly appreciated. Thank you!

**Comment by jxiw** [comment]
Yes. That is really an amazing question!

The reason we have the `mamba` directory is to support arbitrary transformer model distillation from Hugging Face. Some transformer models have specialized components (e.g., sliding window attention, different positional embedding styles, etc.) in their self-attention mechanisms that are not supported by the [mha.py](https://github.com/state-spaces/mamba/blob/main/mamba_ssm/modules/mha.py) from Mamba. We aim to enable training using HuggingFace models without changing their transformer code. 

For `mamba_inference`, some linear layers are fused, and we use [mha.py](https://github.com/state-spaces/mamba/blob/main/mamba_ssm/modules/mha.py) from Mamba, which is optimized for generation performance with static KV cache and other enhancements that differ from the Hugging Face KV cache.

However, the architectures of the two should be exactly the same.

**Comment by 1773226512** [comment]
Thank you for your response! Is the mamba_inference model suitable for lm_eval? I modified the lm_eval_harness.py file to use the inference model, but I am getting different results compared to the original. Could you provide some guidance on this?
```
        from mamba2_inference.hybrid_wrapper import MambaTransformerHybridModelWrapper
        self._model = MambaTransformerHybridModelWrapper.from_pretrained(pretrained, torch_dtype=dtype)
        self.tokenizer = AutoTokenizer.from_pretrained(pretrained)
```

**Comment by jxiw** [comment]
thank you for this question. Could you please tell me the model and whether you use bf16 or fp16. Normally, fp16 gives you better average results. there might be some stability issues. i can try to debug each layer and see the problem.

**Comment by 1773226512** [comment]
I didn't modify the model code in mamba2_inference. The only change I made was importing the model from mamba2_inference, and the default type is set to bf16.

**Comment by jxiw** [comment]
thank you. i guess that there are some inconsistent between HF LlamaFlashAttention2 and Mamba [mha.py](https://github.com/state-spaces/mamba/blob/main/mamba_ssm/modules/mha.py). i will debug and fix that.

**Comment by 1773226512** [comment]
@Thank you very much.  👍

**Comment by jxiw** [comment]
Thanks for this great bug report! I forget the normalization after the decoder layers. Please check the latest code version.

Here are the update results from my run.

| Model                       | Precision | WG    | PIQA  | HellaSwag | ARC-Easy | ARC-Challenge | MMLU  | OpenBook | PubMed | RACE  |
|-----------------------------|-----------|-------|-------|-----------|----------|---------------|-------|----------|--------|-------|
| Mamba-Llama3 (50% att)      | Non Fused (Report) | 68.98 | 78.02 | 78.43     | 74.45    | 51.96         | 57.81 | 44       | 73     | 38.56 |
|                             | Fused BP 16 | 69.06 | 77.97 | 78.47     | 74.45    | 52.05         | 57.78 | 44       | 73.2   | 38.37 |
|                             | Fused FP 16 | 69.22 | 78.07 | 78.69     | 75.42    | 53.41         | 57.86 | 44.2     | 73.4   | 38.85 |
| Mamba2-Llama3 (50% att)     | Non Fused (Report) | 71.51 | 81.45 | 79.47     | 78.83    | 58.19         | 55.7  | 44.2     | 72.4   | 38.85 |
|                             | Fused BP 16 | 71.11 | 81.23 | 79.43     | 78.62    | 58.53         | 55.76 | 44.2     | 72.2   | 38.66 |
|                             | Fused FP 16 | 70.96 | 81.5  | 80.19     | 78.87    | 60.24         | 55.22 | 44       | 71.6   | 39.43 |

If you have further questions, please let me know@
