### ISSUE TITLE
delta_bias must have shape (dim)

### ISSUE THREAD

**Issue by unlabeledData** [jxiw/MambaInLlama#13]
Hi, I try to run the experiment of zephyr in stage 2 SFT. I met the problem in the final evaluation of the SFT.
Do you ever meet the problem of the shape of delta_bias?

'''
RuntimeErrorout, x, *rest = selective_scan_cuda.fwd(u, delta, A, B, C, D, z, delta_bias, delta_softplus)out, x, *rest = selective_scan_cuda.fwd(u, delta, A, B,  C, D, z, delta_bias, delta_softplus):
delta_bias must have shape (dim)
'''

where occured in `/home/user/miniconda3/envs/MambaLlama/lib/python3.10/site-packages/mamba_ssm-2.2.2-py3.10-linux-x86_64.egg/mamba_ssm/ops/selective_scan_interface.py",  line 42, in forward`.

**Comment by unlabeledData** [comment]
> Hi, I try to run the experiment of zephyr in stage 2 SFT. I met the problem in the final evaluation of the SFT. Do you ever meet the problem of the shape of delta_bias?
> 
> ''' RuntimeErrorout, x, *rest = selective_scan_cuda.fwd(u, delta, A, B, C, D, z, delta_bias, delta_softplus)out, x, *rest = selective_scan_cuda.fwd(u, delta, A, B, C, D, z, delta_bias, delta_softplus): delta_bias must have shape (dim) '''
> 
> where occured in `/home/user/miniconda3/envs/MambaLlama/lib/python3.10/site-packages/mamba_ssm-2.2.2-py3.10-linux-x86_64.egg/mamba_ssm/ops/selective_scan_interface.py", line 42, in forward`.

Could you share the 50% SFT model with zephyr? The HF download link is 404 now.

**Comment by jxiw** [comment]
Sure. We actually have a much much better model and we will release that next week.
 
 To get the model in deepspeed, you have to set you checkpoint path 'CHECKPOINT_PATH' and run this
 
 ```
 python ${CHECKPOINT_PATH}/zero_to_fp32.py ${CHECKPOINT_PATH} ${CHECKPOINT_PATH}/pytorch_model.bin
 ```
 
 It will produce a `pytorch_model.bin` for you

**Comment by unlabeledData** [comment]
> Sure. We actually have a much much better model and we will release that next week.
> 
> To get the model in deepspeed, you have to set you checkpoint path 'CHECKPOINT_PATH' and run this
> 
> ```
> python ${CHECKPOINT_PATH}/zero_to_fp32.py ${CHECKPOINT_PATH} ${CHECKPOINT_PATH}/pytorch_model.bin
> ```
> 
> It will produce a `pytorch_model.bin` for you

Thank you. It works.
