### ISSUE TITLE
question about repeat_kv_before_conv

### ISSUE THREAD

**Issue by kibong** [jxiw/MambaInLlama#15]
Thank you for your amazing work.
I have a question about `repeat_kv_before_conv`.
In the implementation, it seems that mamba1's default value for `repeat_kv_before_conv` is true,
while mamba2's default value is false.
I'm curious if there have been any experiments related to this and what the results were.

**Comment by jxiw** [comment]
thank you for this question. it does not influence a lot. We initially think the conv + ssm are both token mixing. So we replace attention with conv + ssm and the repeat_kv happen before conv. Later, we test and find it does not have a lot difference. For performance wise, we move repeat_kv after conv.

**Comment by jxiw** [comment]
Btw, currently, we find mamba1 is easier to mimic and the loss drops faster than mamba 2. But those two should be same in theory.

**Comment by kibong** [comment]
Thank you for your response.

when I tried training with `llama3.2_3B/large_llama3_ft_mamba2_0.5.yaml`,
the KL loss scale seems too large (starting from 20000).
Is this normal?
