### ISSUE TITLE
question about freezing student's MLP!

### ISSUE THREAD

**Issue by kibong** [jxiw/MambaInLlama#18]
in train_mamba2/train_distill.py, train_mamba/train_distill.py
it seems that the student's MLP is not being frozen here (Unlike in train_hybrid.py)
Is this intentional?

**Comment by jxiw** [comment]
thank you for this question. if you want to do a layer by layer distillation, you need to frozen the MLP layers. To make the training faster, i just do a directly distillation. So I don't do the step 1. But if you do that, I get ~2 improvement on MMLU for the llama3 model. For llama3.1, I just use a larger teacher model and ignore the step 1.

**Comment by kibong** [comment]
thank you for response 👍
I learn a lot from your repository and paper!
