### ISSUE TITLE
The effect of use_cache=False on speed

### ISSUE THREAD

**Issue by Yingyue-L** [jxiw/MambaInLlama#19]
I found that the model defaults to setting `use_cache=False` during inference. Doesn't this cause a significant decrease in speed? In a mixed model setup, is there a way to use caching?

**Comment by jxiw** [comment]
thank you. that is a really good question. The problem is that the HF library uses different KV [cache strategy](https://github.com/huggingface/transformers/blob/main/src/transformers/cache_utils.py) compared with Mamba. I haven't figure out how to support HF cache class for Mamba. So what i do is that i convert the checkpoint to the Mamba official repo style and plugin the inference code there. So you should do `from mamba_inference.hybrid_wrapper import MambaTransformerHybridModelWrapper` and `from mamba_inference2.hybrid_wrapper import MambaTransformerHybridModelWrapper`. But their MHA class might only support limited attention.
If you want faster inference, you can also try to check [this](https://github.com/itsdaniele/speculative_mamba).

**Comment by Yingyue-L** [comment]
During evaluation, is the `allocate_inference_cache` function primarily responsible for enabling the use_cache=True setting?

**Comment by adityakotha03** [comment]
Does this mean that the speedup comparisions made in the paper were relative to HF implimentation? Or were the speculative decoding performances were compared to official mamba repo?

**Comment by jxiw** [comment]
Yes. That’s correct.

**Comment by Yingyue-L** [comment]
I noticed that you changed LlamaDecoderLayer to mamba_ssm's MHADecoderLayer. Does this implementation result in lower attention efficiency compared to FlashAttention2?

**Comment by jxiw** [comment]
I don’t think so. The MHA in mamba_Sam call flash attention. The only difference is that the attention cache implementation is compatible with Mamba cache.

**Comment by Yingyue-L** [comment]
> I don’t think so. The MHA in mamba_Sam call flash attention. I think its implementation should be more efficient than HF cache. They use allocate_inference_cache to make attention cache implementation is compatible with Mamba cache.

Thanks for your reply! I have another question, How does the speed of a hybrid model compare to the original model when speculative decoding is not used?

**Comment by jxiw** [comment]
could you please check [this](https://github.com/jxiw/MambaInLlama/blob/main/benchmark/benchmark_generation_speed.py) and [this](https://github.com/jxiw/MambaInLlama/blob/main/benchmark/speed.sh). In my case, i get something like this.

![image](https://github.com/user-attachments/assets/13cdddfa-98e5-499a-b1cf-7e8fde61f741)

**Comment by Yingyue-L** [comment]
> could you please check [this](https://github.com/jxiw/MambaInLlama/blob/main/benchmark/benchmark_generation_speed.py) and [this](https://github.com/jxiw/MambaInLlama/blob/main/benchmark/speed.sh). In my case, i get something like this.
> 
> ![image](https://private-user-images.githubusercontent.com/16102460/393051105-13cdddfa-98e5-499a-b1cf-7e8fde61f741.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0ODQwOTAsIm5iZiI6MTczMzQ4Mzc5MCwicGF0aCI6Ii8xNjEwMjQ2MC8zOTMwNTExMDUtMTNjZGRkZmEtOThlNS00OTlhLWIxY2YtN2U4ZmRlNjFmNzQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDExMTYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlY2VkMjZmNDE3NDdmNTRiMmI3NDJjOWFjNDA1ZGRhYTU3ZWViZmE4ZGE1YWYxNDZlOWUwMmY3Mzc5ZGUyMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oOeNXIFUrU6GImEK2k2rcdRJzVcfnpcsjRJ-ZGPXUGE)

Thanks for your reply!
