### ISSUE TITLE
Request for Implementation Guidance on Hardware-Aware Speculative Decoding in Mamba Models

### ISSUE THREAD

**Issue by adityakotha03** [jxiw/MambaInLlama#3]
Thank you for the amazing work on "The Mamba in the Llama: Distilling and Accelerating Hybrid Models." I am particularly interested in the hardware-aware speculative decoding algorithm described in the paper, especially how it can be applied to the Mamba models during inference.

I would appreciate it if you could provide a more detailed explanation or, steps to replicate the same.

**Comment by jxiw** [comment]
Sure. We will have a separate repository for that! 
@itsdaniele is preparing that. Maybe follow up that with @itsdaniele.

**Comment by adityakotha03** [comment]
Hi @itsdaniele, would like to know if there is any update regarding speculative decoding with mamba. 
Thanks.

**Comment by jxiw** [comment]
thank you for this questions. Daniele is on a vacation now. We will update that next week.

**Comment by adityakotha03** [comment]
> thank you for this questions. Daniele is on a vacation now. We will update that next week.

Hi, any update on this?
Thanks

**Comment by itsdaniele** [comment]
Hi @adityakotha03, sorry about the delay, I was waiting for the Neurips decision. The speculative decoding code will be out by the end of next week.

**Comment by adityakotha03** [comment]
> Hi @adityakotha03, sorry about the delay, I was waiting for the Neurips decision. The speculative decoding code will be out by the end of next week.

Hi any updates on this

**Comment by yjdy** [comment]
> Hi @adityakotha03, sorry about the delay, I was waiting for the Neurips decision. The speculative decoding code will be out by the end of next week.

Hi any updates on this?
Thanks

**Comment by LiJunscs** [comment]
Hi, any updates on this?
Thanks

> Hi @adityakotha03, sorry about the delay, I was waiting for the Neurips decision. The speculative decoding code will be out by the end of next week.

**Comment by cyj95** [comment]
> 

Hi, any updates on this?
Thanks

**Comment by itsdaniele** [comment]
Hi, you can check [this repo](https://github.com/itsdaniele/speculative_mamba)

**Comment by LiJunscs** [comment]
> Hi, you can check [this repo](https://github.com/itsdaniele/speculative_mamba)

Thank you
