### ISSUE TITLE
Some notes on improving HF integration

### ISSUE THREAD

**Issue by NielsRogge** [jxiw/MambaInLlama#4]
Hi,

Niels here from the open-source team at Hugging Face. I discovered your work through the paper page: https://huggingface.co/papers/2408.15237.

Thanks for making the models available on the 🤗 hub. Some small suggestions on how to improve the discoverability of your work:

- would be great to mention the paper's Arxiv or paper page URL in the README. This way, the models get automatically linked to https://huggingface.co/papers/2408.15237, enabling people to view the models from there.
- would be cool to group the models into a [collection](https://huggingface.co/docs/hub/en/collections). See e.g. here for current trending collections: https://huggingface.co/collections.

Let me know if you need any help regarding this!

Cheers,

Niels
ML Engineer @ HF 🤗

**Comment by jxiw** [comment]
Hey Niels,

Thank you for those great suggestions! We did those.

Cheers,
Junxiong

**Comment by NielsRogge** [comment]
Awesome, thanks a lot!
