### ISSUE TITLE
Shape Mismatch &  mamba-ssm==2.1.0 not working

### ISSUE THREAD

**Issue by Mooler0410** [jxiw/MambaInLlama#5]
Hi, 

I'm trying to run the example:

```python 
import torch
from transformers import AutoTokenizer
from mamba2_inference.hybrid_wrapper import MambaTransformerHybridModelWrapper

pretrained_model_name = "JunxiongWang/Mamba2InLlama_0_50" # change the model that you want to test here
model = MambaTransformerHybridModelWrapper.from_pretrained(pretrained_model_name, torch_dtype=torch.bfloat16)
model.eval()

messages = [[
    {
        "role": "user",
        "content": "## Question: \n\nFarmer Brown has 20 animals on his farm, all either chickens or cows. They have a total of 70 legs, all together. How many of the animals are chickens? ## Instruction \n\nPlease answer this question by first reasoning and then providing your answer.",
    },
]]

tokenizer = AutoTokenizer.from_pretrained(pretrained_model_name)
formatted_prompts = [
    tokenizer.apply_chat_template(message, tokenize=False, add_generation_prompt=True) for message in messages
]

prompts = [
    tokenizer.encode(formatted_prompt, return_tensors="pt", truncation=True, max_length=200)
    for formatted_prompt in formatted_prompts
]
batch_prompts = torch.cat(prompts, dim=0).cuda()

outputs = model.generate(
    input_ids=batch_prompts,
    max_length=1000,
    cg=True,
    return_dict_in_generate=True,
    output_scores=True,
    enable_timing=True,
    top_k=1,
    eos_token_id=tokenizer.eos_token_id
)

generated_text = tokenizer.batch_decode(outputs.sequences.tolist())
print(generated_text[0])

#output:
#**Step 1:** Let's denote the number of chickens as C and the number of cows as K.
#**Step 2:** Chickens have 2 legs each, and cows have 4 legs each. We can create an equation based on the total number of legs:
#2C (chicken legs) + 4K (cow legs) = 70 legs
#**Step 3:** We also know that there are 20 animals in total:
#C + K = 20
#**Step 4:** Solve the second equation for one variable, let's say K:
#K = 20 - C
#**Step 5:** Substitute the expression for K in the first equation:
#2C + 4(20 - C) = 70
#**Step 6:** Simplify and solve for C:
#2C + 80 - 4C = 70
#-2C = -10
#C = 5
#**Conclusion:** There are 5 chickens on Farmer Brown's farm.
```

First, I get the error that there is no argument named as 'cu_seqlens' for 'mamba_chunk_scan_combined'. 

I found that the API is different in mamba-ssm==2.1.0, which is recommended by the environment file. So I upgraded it to 2.2.0, and bypass this error. But I encountered another shape mismatch error:

```python
  File "/home/hongyjin/.local/lib/python3.10/site-packages/mamba_ssm/ops/triton/ssd_combined.py", line 287, in _mamba_chunk_scan_combined_fwd
    assert dt.shape == (batch, seqlen, nheads)
AssertionError
```
Do you have any suggestions about this issue?
Thanks!

**Comment by jxiw** [comment]
Yes. We used mamba==2.1.0 for mamba 1 training. But later we switch to mamba2, and we update our ssm to 2.2.2.
But i forget to update this version requirements in the file. I am sorry for that.

**Comment by Mooler0410** [comment]
Thanks! Will try it!

**Comment by jxiw** [comment]
are you use flash_attention? Could you please try

```
from flash_attn import flash_attn_with_kvcache
```

I think if your flash_attention setup correctly, you should not reach that code. please let me know if you any further questions.

**Comment by jxiw** [comment]
From here, https://github.com/state-spaces/mamba/blob/main/mamba_ssm/modules/mha.py#L279-L284, It seems you `inference_params is None`. I think the inference param should be init before running to here.

**Comment by Mooler0410** [comment]
Hi, thanks for the quick reply! I figured out that the excution of this line is triggered by : i
```python
inference_params.seqlen_offset == 0
```
*flash_attn_with_kvcache* works well.

**Comment by jxiw** [comment]
Hi, i am a bit confused.

Did you fix your problem?

I don't see any place using "inference_params.seqlen_offset"

Thanks.

**Comment by Mooler0410** [comment]
Sorry for the confusing reply. Following your suggestion, I dived into mamba_ssm's code, the error is triggered at:
https://github.com/state-spaces/mamba/blob/8ffd905c91d207f5c0cc84fc2a2fb748655094f0/mamba_ssm/modules/mha.py#L282C1-L282C17

for **mamba_ssm==2.2.2**, it's:
```python
            if inference_params is None:
                k, v = kv.unbind(dim=-3)
                context = F.scaled_dot_product_attention(
                    q.transpose(1, 2), k.transpose(1, 2), v.transpose(1, 2), is_causal=self.causal, scale=self.softmax_scale
                ).transpose(1, 2)
            else:
                context = self._update_kvcache_attention(q, kv, inference_params) # line 282
        else:
```
Then, I went to *_update_kvcache_attention*:
```python
        if (
            inference_params.seqlen_offset == 0
            or flash_attn_with_kvcache is None
        ):
            # TODO: this only uses seqlen_offset and not lengths_per_sample.
            kv = self._update_kv_cache(kv, inference_params)
            k, v = kv.unbind(dim=-3)
            return F.scaled_dot_product_attention(
                q.transpose(1, 2), k.transpose(1, 2), v.transpose(1, 2), is_causal=self.causal, scale=self.softmax_scale
            ).transpose(1, 2)
        else:
```
The error happens at the line of:
```python
            return F.scaled_dot_product_attention(
                q.transpose(1, 2), k.transpose(1, 2), v.transpose(1, 2), is_causal=self.causal, scale=self.softmax_scale
            ).transpose(1, 2)
```
because of the condition: **inference_params.seqlen_offset == 0**

I have no idea about how this could happen.

**Comment by jxiw** [comment]
Hi, i am able to reproduce your issue. 

the issue is because `mamba-ssm==2.2.2` is installed using pip instead of build from the source. 

The pip version (July 3) does not support GQA which is used in llama and they are able to fix that in this commit (https://github.com/state-spaces/mamba/commit/014c094d11f780a27330657faabecaaded7a31db).

In order to support GQA, you have to build from your resource and use the version after this commit.

Thanks for raising this issue.

**Comment by Mooler0410** [comment]
It works! Thank you so much!
