### ISSUE TITLE
Mamba Model initialisation

### ISSUE THREAD

**Issue by aashay-sarvam** [jxiw/MambaInLlama#8]
How is the mamba model being initialised?

<img width="981" alt="Screenshot 2024-09-11 at 7 08 06 PM" src="https://github.com/user-attachments/assets/112d0f96-bb30-47f2-95bc-221bda86d38f">

In the paper it is suggested the model at the start gets some initialisation from the transformer, but I don't see it in the code.

**Comment by jxiw** [comment]
Hi aashay,

Thanks for raising this problem. Here is a long answer.

If you follow of 3 steps training. Assume in the first step, we are going to distill models using pseudo label distillation. We set the init_with_kqvo to true. This part will be executed. https://github.com/jxiw/MambaInLlama/blob/main/mamba/hybrid_wrapper.py#L38-L46

If you skip the first step, only do SFT and DPO. We still initialize linear layers of model using this https://github.com/jxiw/MambaInLlama/blob/main/train_mamba/train_sft.py#L198-L199.

Best,
Junxiong
